### ISSUE TITLE
Cannot create environment (conda issue installing PyG)

### ISSUE THREAD

**Issue by iaaka** [paulmorio/GNN-C2L#1]
Hello, thank you for this tool, unfortunately I encountered a problem when I tried to build an environment according for your instructions, it seems like there is something wrong with `pyg` channel (see below). Is there any chance you can provide docker/singularity image for the tool? dockerfile or yml can be also useful.
```
conda install pyg -c pyg
Collecting package metadata (current_repodata.json): failed  

 #>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<< 

    Traceback (most recent call last):
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 187, in conda_http_errors
        yield
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 153, in repodata
        response.raise_for_status()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://conda.anaconda.org/pyg/linux-64/current_repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/requests/models.py", line 971, in json
        return complexjson.loads(self.text, **kwargs)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/simplejson/__init__.py", line 514, in loads
        return _default_decoder.decode(s)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/simplejson/decoder.py", line 386, in decode
        obj, end = self.raw_decode(s)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/simplejson/decoder.py", line 416, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, p)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 126, in do_call
        return getattr(module, func_name)(args, parser)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 123, in wrapper
        return func(*args, **kwargs)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/cli/main_install.py", line 22, in execute
        install(args, parser, "install")
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 309, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 153, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 214, in solve_for_diff
        final_precs = self.solve_final_state(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 357, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 83, in decorated
        return f(*args, **kwds)
File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 571, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1285, in _prepare
        reduced_index = get_reduced_index(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 286, in get_reduced_index
        new_records = SubdirData.query_all(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 157, in query_all
        result = tuple(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
        return self.__get_result()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 142, in subdir_query
        return tuple(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 164, in query
        self.load()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 321, in _load
        repodata, state = fetcher.fetch_latest_parsed()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 757, in fetch_latest_parsed
        parsed, state = self.fetch_latest()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 879, in fetch_latest
        raw_repodata = repo.repodata(cache.state)  # type: ignore
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 153, in repodata
        response.raise_for_status()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/contextlib.py", line 137, in __exit__
        self.gen.throw(typ, value, traceback)
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 234, in conda_http_errors
        raise RepodataIsEmpty(
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 527, in __init__
        body = response.json()
      File "/nfs/cellgeni/pasham/miniconda3/lib/python3.9/site-packages/requests/models.py", line 975, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)   
    requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=gnnc2l_env
                CONDA_EXE=/nfs/cellgeni/pasham/miniconda3/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/nfs/cellgeni/pasham/miniconda3/envs/gnnc2l_env
           CONDA_PREFIX_1=/nfs/cellgeni/pasham/miniconda3
    CONDA_PROMPT_MODIFIER=(gnnc2l_env)
         CONDA_PYTHON_EXE=/nfs/cellgeni/pasham/miniconda3/bin/python
               CONDA_ROOT=/nfs/cellgeni/pasham/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/software/lsf-farm5/10.1/linux3.10-glibc2.17-x86_64/lib:/usr/lib/oracl
                          e/12.1/client64/lib
               LD_PRELOAD=<not set>
    MAGICK_CONFIGURE_PATH=/nfs/users/nfs_p/pm19/.ImageMagic  
                  MANPATH=/usr/local/lsf/10.1/man:::
               MODULEPATH=/etc/environment-modules/modules:/usr/share/modules/versions:/usr/shar
                          e/modules/$MODULE_VERSION/modulefiles:/usr/share/modules/modulefiles
                     PATH=/software/lsf-farm5/10.1/linux3.10-glibc2.17-x86_64/bin:/nfs/cellgeni/
                          pasham/miniconda3/envs/gnnc2l_env/bin:/nfs/cellgeni/pasham/miniconda3/
                          condabin:/usr/lib/oracle/12.1/client64/bin:/software/lsf-farm5/10.1/li
                          nux3.10-glibc2.17-x86_64/etc:/usr/local/sbin:/usr/local/bin:/usr/sbin:
                          /usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/softwa
                          re/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : gnnc2l_env
    active env location : /nfs/cellgeni/pasham/miniconda3/envs/gnnc2l_env
            shell level : 2
       user config file : /nfs/users/nfs_p/pm19/.condarc
 populated config files : /nfs/users/nfs_p/pm19/.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.2=0
                          __glibc=2.27=0
                          __linux=4.15.0=0
                          __unix=0=0
       base environment : /nfs/cellgeni/pasham/miniconda3  (writable)
      conda av data dir : /nfs/cellgeni/pasham/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pyg/linux-64
                          https://conda.anaconda.org/pyg/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /nfs/cellgeni/pasham/miniconda3/pkgs
(gnnc2l_env) pm19@farm5-gpu0105:~/nfs/projects/2306.gnn.c2l$ 
```

**Comment by paulmorio** [comment]
Hello @iaaka , thanks for looking at our work!

Yes the PyG installation to an environment can be somewhat sensitive at times depending on Python/PyTorch + `conda` or `pip` installation procedures performed.

Briefly looking at the error report I can see that the environment was not constructed as in the instructions, with Python 3.9 and CUDA 11.2 instead of Python 3.7 and CUDA 11.7.

For now could you try again with the exact terminal commands as in the README? I will also look into doing the setup with Python 3.9 if this is critical to your work next week.

As an additional note: we will be looking into refactoring the codebase, where the newer python versions will be a consideration.

Let me know if this helps!

Best,
paulmorio

**Comment by iaaka** [comment]
Hi Paul, I just followed your instructions
```
conda create -n gnnc2l_env python=3.7
conda activate gnnc2l_env
conda install -y pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
conda install pyg -c pyg
```
I believe that it is python3.7 environment, at least it is what it says:
```
(gnnc2l_env)$ python --version
Python 3.7.12
```
I'm not quite sure but it seems for me that `miniconda3/lib/python3.9` from error report above is not python used within the environment but rather some conda housekeeping thing.
Could it be something about conda version? mine is `conda 23.5.0`

**Comment by paulmorio** [comment]
Hello @iaaka ,

My conda version is 4.14.0 and just tried a fresh environment creation with the instructions and it went through, so perhaps it is to do with the dependency management in the new conda versions. I will look into doing this for your conda version. 

Best,
paulmorio

**Comment by paulmorio** [comment]
Update: I have made a fresh install of Miniconda3  (conda 23.3.1) (which is latest stable for Linux 64bit as on https://docs.conda.io/en/latest/miniconda.html) on a separate machine. Then followed the instructions as on README and it was fine.

Perhaps there is an issue with your conda installation? 

(Edit: This is the specific installer used for the new Miniconda3 (https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh))

**Comment by iaaka** [comment]
Hi Paul, thank you, my  conda somehow updated to too advanced version. Installation worked after I downgraded it to 23.3.1. 
I want to compare gnn-c2l results with c2l for several samples, however I cannot find any instructions on how to run gnn-c2l on specific sample starting from visium h5ad and reference signature (preferably as csv,  but from h5ad would be also ok). Could you please help me with it? some examples would be very usefull.

**Comment by paulmorio** [comment]
Hello @iaaka ,

I am glad we got through the installation :)

Sure thing, you can look and perhaps adapt this script to play with your own datas (https://github.com/paulmorio/GNN-C2L/blob/main/experiments/comparative_eval/args_run_c2l.py). You can find examples of how it was done for the MPOA and Xenium dataset as in the paper there too. Historical note: we built these scripts off the notebooks in the original cell2location paper (https://github.com/vitkl/cell2location_paper/tree/master/notebooks).

Best,
paulmorio
